# Generated by Django 5.0.1 on 2024-02-04 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="seller_id",
            new_name="seller",
        ),
    ]
